
env:
  # window: "SDL2"
  window: "null"
  ROM: "ROM/PokemonRed.gb"
  initial_state_file: "ROM/PokemonRed.gb.state"

network:
  num_eps: 1000
  epsilon: 0.5
  max_step: 200
  train_every_n: 1000
  batch_size: 3000
  initial_fill: 500
  save_every_n: 100000
  discount: 0.99
  lr: 0.000001
  saved_weights: null
  # saved_weights: "weights/weights1_100000_6in"
  save_root: "weights/weights1"
  best_state_file: "ROM/best_state.state"
  running_screenshot: "screenshot.png"
  reward_screenshots: "reward_flags"